name: build-and-deploy.yml
on:
  push:
    branches: [ "*", "main", "dev" ]
  pull_request:
    branches: [ "*", "main", "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26'

      - name: Build
        run: go build -v -o ./build/invoice-gen ./cmd/main.go

      - name: Test
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy to Remote Server
        uses: pierrickdelrieu/scp-action@v0.1.0
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          ssh_port: ${{ secrets.DESTINATION_SSH_PORT }}
          ssh_username: ${{ secrets.SSH_USERNAME }}
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source_dir: "./build"
          destination_dir: "~/build"
          rm: true