name: build-and-deploy.yml
on:
  push:
    branches: [ "*", "main", "dev" ]
  pull_request:
    branches: [ "*", "main", "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26'

      - name: Build
        run: go build -v -o ./build/invoice-gen ./cmd/main.go

      - name: Test
        run: go test -v ./...

      - name: Upload build folder via SCP
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.DESTINATION_HOST }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PORT: ${{ secrets.DESTINATION_SSH_PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -p ${SSH_PORT:-22} $SSH_HOST >> ~/.ssh/known_hosts

          scp -P ${SSH_PORT:-22} -r ./build \
            $SSH_USER@$SSH_HOST:~/build